<a href="https://colab.research.google.com/github/ahsal075/ahsal/blob/main/ahsal_pandas_casestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1) Import pandas, numpy

In [46]:
import pandas as pd
import numpy as np
url = "https://raw.githubusercontent.com/laxmimerit/All-CSV-ML-Data-Files-Download/master/IMDB-Movie-Data.csv"
df = pd.read_csv(url)

## 2) Load dataset using pd.read_csv()

In [47]:
url = "https://raw.githubusercontent.com/laxmimerit/All-CSV-ML-Data-Files-Download/master/IMDB-Movie-Data.csv"
df = pd.read_csv(url)

## 3) Display: shape, head, column names, datatypes, missing value

## Shape

In [48]:
df.shape

(1000, 12)

## Head

In [49]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

##  Columns

In [51]:
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

##  Data type

In [52]:
df.dtypes

Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object

##  Missing value

In [53]:
df.isna().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

## 4) Check and remove duplicates

In [54]:
df.drop_duplicates(inplace=True)
df.shape

(1000, 12)

## 5) Rename columns ("Title" > "Movie_Title")

In [72]:
df.rename(columns={"Title": "Movie_Title"}, inplace=True)
df.head()

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Num_Genres,Profitability,Rating_Category
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,3,2.753140,Good
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,3,1.019839,Average
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,2,1.180513,Average
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,3,2.502963,Average
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,3,2.642439,Average

## 6) Get unique genres

In [56]:
genres = df['Genre'].str.split(',').explode()
unique_genres = genres.unique()
unique_genres

array(['Action', 'Adventure', 'Sci-Fi', 'Mystery', 'Horror', 'Thriller',
       'Animation', 'Comedy', 'Family', 'Fantasy', 'Drama', 'Music',
       'Biography', 'Romance', 'History', 'Crime', 'Western', 'War',
       'Musical', 'Sport'], dtype=object)

## 7) Extract number of genres per movie

In [77]:
df['Num_Genres'] = df['Genre'].str.split(',').apply(len)
df.head()

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Num_Genres,Profitability,Rating_Category
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,3,2.753140,Good
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,3,1.019839,Average
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,2,1.180513,Average
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,3,2.502963,Average
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,3,2.642439,Average

## 8) Handle missing values in 'Revenue (Millions)' and 'Metascore

In [78]:
df['Revenue (Millions)'] = df['Revenue (Millions)'].fillna(df['Revenue (Millions)'].mean())
df['Metascore'] = df['Metascore'].fillna(df['Metascore'].mean())

print(df[['Revenue (Millions)','Metascore']].head())
print(df[['Revenue (Millions)','Metascore']].isnull().sum())

   Revenue (Millions)  Metascore
0              333.13       76.0
1              126.46       65.0
2              138.12       62.0
3              270.32       59.0
4              325.02       40.0
Revenue (Millions)    0
Metascore             0
dtype: int64

## 9) Top 5 movies by Rating

In [79]:
top_5_movies_by_rating = df.sort_values(by='Rating', ascending=False).head(5)
top_5_movies_by_rating

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Num_Genres,Profitability,Rating_Category
54,55,The Dark Knight,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.000000,3,3.508684,Good
80,81,Inception,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.000000,3,1.976824,Good
117,118,Dangal,"Action,Biography,Drama",Former wrestler Mahavir Singh Phogat and his t...,Nitesh Tiwari,"Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...",2016,161,8.8,48969,11.15,58.985043,3,0.069255,Good
36,37,Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.000000,3,1.112367,Good
249,250,The Intouchables,"Biography,Comedy,Drama",After he becomes a quadriplegic from a paragli...,Olivier Nakache,"François Cluzet, Omar Sy, Anne Le Ny, Audrey F...",2011,112,8.6,557965,13.18,57.000000,3,0.117679,Good

## 10) Movies with highest/lowest revenue

In [61]:
highest_revenue_movies = df.sort_values(by='Revenue (Millions)', ascending=False).head(5)
highest_revenue_movies
lowest_revenue_movies = df.sort_values(by='Revenue (Millions)', ascending=True).head(5)
lowest_revenue_movies

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Num_Genres
231,232,A Kind of Murder,"Crime,Drama,Thriller","In 1960s New York, Walter Stackhouse is a succ...",Andy Goddard,"Patrick Wilson, Jessica Biel, Haley Bennett, V...",2016,95,5.2,3305,0.00,50.000000,3
27,28,Dead Awake,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,58.985043,2
68,69,Wakefield,Drama,A man's nervous breakdown causes him to leave ...,Robin Swicord,"Bryan Cranston, Jennifer Garner, Beverly D'Ang...",2016,106,7.5,291,0.01,61.000000,1
961,962,Into the Forest,"Drama,Sci-Fi,Thriller","After a massive power outage, two sisters lear...",Patricia Rozema,"Ellen Page, Evan Rachel Wood, Max Minghella,Ca...",2015,101,5.9,10220,0.01,59.000000,3
321,322,Lovesong,Drama,The relationship between two friends deepens d...,So Yong Kim,"Riley Keough, Jena Malone, Jessie Ok Gray, Car...",2016,84,6.4,616,0.01,74.000000,1

## 11) Avg. rating by Director

In [62]:
avg_rating_by_director = df.groupby('Director')['Rating'].mean().reset_index()
avg_rating_by_director.columns = ['Director', 'Average_Rating']
avg_rating_by_director

                Director  Average_Rating
0             Aamir Khan            8.50
1    Abdellatif Kechiche            7.80
2              Adam Leon            6.50
3             Adam McKay            7.00
4          Adam Shankman            6.30
..                   ...             ...
639         Xavier Dolan            7.55
640          Yimou Zhang            6.10
641     Yorgos Lanthimos            7.20
642          Zack Snyder            7.04
643        Zackary Adler            5.10

[644 rows x 2 columns]

## 12) Movies per year

In [63]:
movies_per_year = df['Year'].value_counts().sort_index()
movies_per_year

Year
2006     44
2007     53
2008     52
2009     51
2010     60
2011     63
2012     64
2013     91
2014     98
2015    127
2016    297
Name: count, dtype: int64

## 13) Movies with rating > 8 & revenue > 100M

In [64]:
movies_filtered = df[(df['Rating'] > 8) & (df['Revenue (Millions)'] > 100)]
movies_filtered

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Num_Genres
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.000000,3
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.000000,3
36,37,Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.000000,3
50,51,Star Wars: Episode VII - The Force Awakens,"Action,Adventure,Fantasy",Three decades after the defeat of the Galactic...,J.J. Abrams,"Daisy Ridley, John Boyega, Oscar Isaac, Domhna...",2015,136,8.1,661608,936.63,81.000000,3
54,55,The Dark Knight,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.000000,3
67,68,Mad Max: Fury Road,"Action,Adventure,Sci-Fi",A woman rebels against a tyrannical ruler in p...,George Miller,"Tom Hardy, Charlize Theron, Nicholas Hoult, Zo...",2015,120,8.1,632842,153.63,90.000000,3
74,75,Zootopia,"Animation,Adventure,Comedy","In a city of anthropomorphic animals, a rookie...",Byron Howard,"Ginnifer Goodwin, Jason Bateman, Idris Elba, J...",2016,108,8.1,296853,341.26,78.000000,3
76,77,The Avengers,"Action,Sci-Fi",Earth's mightiest heroes must come together an...,Joss Whedon,"Robert Downey Jr., Chris Evans, Scarlett Johan...",2012,143,8.1,1045588,623.28,69.000000,2
77,78,Inglourious Basterds,"Adventure,Drama,War","In Nazi-occupied France during World War II, a...",Quentin Tarantino,"Brad Pitt, Diane Kruger, Eli Roth,Mélanie Laurent",2009,153,8.3,959065,120.52,69.000000,3
80,81,Inception,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.000000,3
82,83,The Wolf of Wall Street,"Biography,Comedy,Crime","Based on the true story of Jordan Belfort, fro...",Martin Scorsese,"Leonardo DiCaprio, Jonah Hill, Margot Robbie,M...",2013,180,8.2,865134,116.87,75.000000,3
83,84,Gone Girl,"Crime,Drama,Mystery",With his wife's disappearance having become th...,David Fincher,"Ben Affleck, Rosamund Pike, Neil Patrick Harri...",2014,149,8.1,636243,167.74,79.000000,3
92,93,The Help,Drama,An aspiring author during the civil rights mov...,Tate Taylor,"Emma Stone, Viola Davis, Octavia Spencer, Bryc...",2011,146,8.1,342429,169.71,62.000000,1
99,100,The Departed,"Crime,Drama,Thriller",An undercover cop and a mole in the police att...,Martin Scorsese,"Leonardo DiCaprio, Matt Damon, Jack Nicholson,...",2006,151,8.5,937414,132.37,85.000000,3
114,115,Harry Potter and the Deathly Hallows: Part 2,"Adventure,Drama,Fantasy","Harry, Ron and Hermione search for Voldemort's...",David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, M...",2011,130,8.1,590595,380.96,87.000000,3
124,125,The Dark Knight Rises,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.000000,2
138,139,Shutter Island,"Mystery,Thriller","In 1954, a U.S. marshal investigates the disap...",Martin Scorsese,"Leonardo DiCaprio, Emily Mortimer, Mark Ruffal...",2010,138,8.1,855604,127.97,63.000000,2
144,145,Django Unchained,"Drama,Western","With the help of a German bounty hunter , a fr...",Quentin Tarantino,"Jamie Foxx, Christoph Waltz, Leonardo DiCaprio...",2012,165,8.4,1039115,162.80,81.000000,2
241,242,Inside Out,"Animation,Adventure,Comedy",After young Riley is uprooted from her Midwest...,Pete Docter,"Amy Poehler, Bill Hader, Lewis Black, Mindy Ka...",2015,95,8.2,416689,356.45,94.000000,3
427,428,The Bourne Ultimatum,"Action,Mystery,Thriller",Jason Bourne dodges a ruthless CIA official an...,Paul Greengrass,"Matt Damon, Edgar Ramírez, Joan Allen, Julia S...",2007,115,8.1,525700,227.14,85.000000,3
499,500,Up,"Animation,Adventure,Comedy",Seventy-eight year old Carl Fredricksen travel...,Pete Docter,"Edward Asner, Jordan Nagai, John Ratzenberger,...",2009,96,8.3,722203,292.98,88.000000,3
634,635,WALL·E,"Animation,Adventure,Family","In the distant future, a small waste-collectin...",Andrew Stanton,"Ben Burtt, Elissa Knight, Jeff Garlin, Fred Wi...",2008,98,8.4,776897,223.81,58.985043,3
645,646,Gran Torino,Drama,Disgruntled Korean War veteran Walt Kowalski s...,Clint Eastwood,"Clint Eastwood, Bee Vang, Christopher Carley,A...",2008,116,8.2,595779,148.09,58.985043,1
688,689,Toy Story 3,"Animation,Adventure,Comedy",The toys are mistakenly delivered to a day-car...,Lee Unkrich,"Tom Hanks, Tim Allen, Joan Cusack, Ned Beatty",2010,103,8.3,586669,414.98,92.000000,3
772,773,How to Train Your Dragon,"Animation,Action,Adventure",A hapless young Viking who aspires to hunt dra...,Dean DeBlois,"Jay Baruchel, Gerard Butler,Christopher Mintz-...",2010,98,8.1,523893,217.39,74.000000,3

## 14) Group by Director: avg Rating, Revenue

In [65]:
group_by_director = df.groupby('Director')[['Rating', 'Revenue (Millions)']].mean().reset_index()
group_by_director.columns = ['Director', 'Average_Rating', 'Average_Revenue']
group_by_director

                Director  Average_Rating  Average_Revenue
0             Aamir Khan            8.50         1.200000
1    Abdellatif Kechiche            7.80         2.200000
2              Adam Leon            6.50        82.956376
3             Adam McKay            7.00       109.535000
4          Adam Shankman            6.30        78.665000
..                   ...             ...              ...
639         Xavier Dolan            7.55        43.223188
640          Yimou Zhang            6.10        45.130000
641     Yorgos Lanthimos            7.20         4.405000
642          Zack Snyder            7.04       195.148000
643        Zackary Adler            5.10         6.530000

[644 rows x 3 columns]

## 15) Group by Year: count, avg Rating

In [66]:
group_by_year = df.groupby('Year').agg(
    Count=('Movie_Title', 'size'),
    Average_Rating=('Rating', 'mean')
).reset_index()
group_by_year

    Year  Count  Average_Rating
0   2006     44        7.125000
1   2007     53        7.133962
2   2008     52        6.784615
3   2009     51        6.960784
4   2010     60        6.826667
5   2011     63        6.838095
6   2012     64        6.925000
7   2013     91        6.812088
8   2014     98        6.837755
9   2015    127        6.602362
10  2016    297        6.436700

16) Create a new column Profitability:

a) Revenue divided by Duration

b) Find top 10 most profitable movies

In [67]:
df['Profitability'] = df['Revenue (Millions)'] / df['Runtime (Minutes)']
top_10_profitable_movies = df.sort_values(by='Profitability', ascending=False).head(10)
top_10_profitable_movies[['Movie_Title', 'Revenue (Millions)', 'Runtime (Minutes)', 'Profitability']]

,Movie_Title,Revenue (Millions),Runtime (Minutes),Profitability
50,Star Wars: Episode VII - The Force Awakens,936.63,136,6.886985
85,Jurassic World,652.18,124,5.259516
119,Finding Dory,486.29,97,5.013299
87,Avatar,760.51,162,4.694506
76,The Avengers,623.28,143,4.358601
15,The Secret Life of Pets,368.31,87,4.233448
688,Toy Story 3,414.98,103,4.028932
12,Rogue One,532.17,133,4.001278
174,Frozen,400.74,102,3.928824
797,Despicable Me 2,368.05,98,3.755612

## 17) Create a column that categorizes movies by rating:
a) Rating < 6: Poor

b) 6 ≤ Rating < 7.5: Average

In [68]:
df['Rating_Category'] = df['Rating'].apply(lambda x: 'Poor' if x < 6 else ('Average' if 6 <= x < 7.5 else 'Good'))
df.head()

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Num_Genres,Profitability,Rating_Category
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,3,2.753140,Good
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,3,1.019839,Average
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,2,1.180513,Average
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,3,2.502963,Average
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,3,2.642439,Average

## 17) Create a column that categorizes movies by rating:
a) Rating < 6: Poor

b) 6 ≤ Rating < 7.5: Average

In [69]:
df['Rating_Category'] = df['Rating'].apply(lambda x: 'Poor' if x < 6 else ('Average' if 6 <= x < 7.5 else 'Good'))
df.head()

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Num_Genres,Profitability,Rating_Category
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,3,2.753140,Good
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,3,1.019839,Average
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,2,1.180513,Average
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,3,2.502963,Average
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,3,2.642439,Average